apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellospring-deployment
spec:
  replicas: 1  # Number of instances (pods) to run
  selector:
    matchLabels:
      app: hellospring
  template:
    metadata:
      labels:
        app: hellospring
    spec:
      containers:
      - name: hellospring
        image: springimg01:latest # Replace with your Docker image name
        imagePullPolicy: IfNotPresent  
        
        ports:
        - containerPort: 9400  # Port that your Spring Boot application listens on inside the container
