server:
  port: 9003

spring:
  application:
    name: STUDENT-SERVICE
 # zipkin:
    #base-url: http://127.0.0.1:9411/
  
  jpa:
    database : mysql
    hibernate.ddl-auto: update
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   registryFetchIntervalSeconds: 5
   healthcheck.enabled: true
   serviceUrl:
#    defaultZone: http://${EUREKA_MAC:localhost}:8761/eureka/
    defaultZone: http://172.25.0.2:8761/eureka/
  instance:
      preferIpAddress: true  