
services:
 springboot-categoryapp:
   image: category
   restart: always
   build: .
   ports:
     - 9700:9700
     
   networks:
      - my-bridge-net  
  # networks:
  #    - proxynet
   depends_on:
      - mysqlcategorydb
   environment:
      MYSQL_HOST: mysqldbcontainer
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: P@ssw0rd
   #   EUREKA_MAC: eureka-conappname
      
 mysqlcategorydb:
   container_name: mysqldbcontainer 
   image: mysql 
   
   ports:
      - 3308:3306
   environment: 
      MYSQL_DATABASE: categorydockdb
      MYSQL_ROOT_PASSWORD: P@ssw0rd
   networks:
      - my-bridge-net
      
      
networks:
  my-bridge-net:
      external: true 